### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by peaceknight05** [relevance/rcov#103]
I'm running Mac OSX High Sierra 10.13.4 (17E199). I am using RVM and ruby 2.4.1
When I type in `gem install rcov` it gives me an error. Inside .rvm/gems/ruby-2.4.1/extensions/x86_64-darwin-17/2.4.0/rcov-1.0.0/gem_make.out it gives me an error report saying,

current directory: /Users/jonathantan/.rvm/gems/ruby-2.4.1/gems/rcov-1.0.0/ext/rcovrt
/Users/jonathantan/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20180501-9065-4si7ik.rb extconf.rb
creating Makefile

current directory: /Users/jonathantan/.rvm/gems/ruby-2.4.1/gems/rcov-1.0.0/ext/rcovrt
make "DESTDIR=" clean

current directory: /Users/jonathantan/.rvm/gems/ruby-2.4.1/gems/rcov-1.0.0/ext/rcovrt
make "DESTDIR="
compiling 1.8/callsite.c
1.8/callsite.c:2:10: fatal error: 'env.h' file not found
#include <env.h>
         ^~~~~~~
1 error generated.
make: *** [callsite.o] Error 1

make failed, exit code 2

Am I using the wrong version of Ruby or is it something else? Any help appreciated. Thanks in advance!

**Comment by retrography** [comment]
The same here

**Comment by isikyus** [comment]
> I am using RVM and ruby 2.4.1

This repository hasn't been updated since 2012; I don't think it supports Ruby 2.4.1

The README recommends using SimpleCov if you're on Ruby 1.9, and I believe it supports 2.x versions as well:

> NOTE: This fork does not work on Ruby 1.9.x. For coverage on Ruby 1.9 look at [SimpleCov](https://github.com/colszowka/simplecov).

**Comment by emmahyde** [comment]
Hello, I am using asdf and ruby 2.6.6, relatively mordern tooling, etc. and still getting this error. Seems like there is a missing header fike the in C.

**Comment by bublik** [comment]
The same problem for ruby 2.7
`Building native extensions. This could take a while...
ERROR:  Error installing rcov:
        ERROR: Failed to build gem native extension.

    current directory: /Users/ruslan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rcov-1.0.0/ext/rcovrt
/Users/ruslan/.rbenv/versions/2.7.2/bin/ruby -I /Users/ruslan/.rbenv/versions/2.7.2/lib/ruby/2.7.0 -r ./siteconf20221121-44222-pj0k0u.rb extconf.rb
creating Makefile

current directory: /Users/ruslan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rcov-1.0.0/ext/rcovrt
make "DESTDIR=" clean

current directory: /Users/ruslan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rcov-1.0.0/ext/rcovrt
make "DESTDIR="
compiling 1.8/callsite.c
1.8/callsite.c:2:10: fatal error: 'env.h' file not found
#include <env.h>
         ^~~~~~~
1 error generated.
make: *** [callsite.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/ruslan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rcov-1.0.0 for inspection.
Results logged to /Users/ruslan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-19/2.7.0/rcov-1.0.0/gem_make.out
`
