### ISSUE TITLE
Failure to build rcov with ruby 2.0.0 (Rails 4/RVM)

### ISSUE THREAD

**Issue by jdee** [relevance/rcov#99]
I get this error when running bundle install with rcov and ruby 2.0.0 (Rails 4/RVM).
Installing rcov (0.9.11) 

```
  Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

  /Users/jdee/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb 
  creating Makefile

  make "DESTDIR="
  compiling 1.8/callsite.c
  1.8/callsite.c:2:10: fatal error: 'env.h' file not found
  #include <env.h>
         ^
  1 error generated.
  make: *** [callsite.o] Error 1
```

I can install properly with ruby 1.9.3, but Rails 4 recommends 2.0, and I'm having some other problems with 1.9.3. For now, I'll eliminate rcov from my bundle.

**Comment by tarumalik** [comment]
I too get this error.. any solution available to fix this?

Pls share

**Comment by jdee** [comment]
I'm not certain if this repo is actively updated. The last code update was a year ago. I switched to [simplecov](http://rubydoc.info/gems/simplecov/frames), which has worked well.

**Comment by abedra** [comment]
RCov does not work with Ruby 1.9+. Please use simplecov.

**Comment by tarumalik** [comment]
okay, thanks..

**Comment by kennym** [comment]
thanks for pointing out to use simplecov.
